export const IPC_SELECT_FILE = 'IPC_SELECT_FILE';
export const IPC_WRITE_FILE = 'IPC_WRITE_FILE';
export const IPC_MESSAGE_ERROR = 'IPC_MESSAGE_ERROR';
export const IPC_MESSAGE_SUCCESS = 'IPC_MESSAGE_SUCCESS';
export const IPC_DECRYPT_CONTENT = 'IPC_DECRYPT_CONTENT';
